services:
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    build:
      context: frontend
      dockerfile: Dockerfile
  db:
    container_name: db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - quiz-db:/var/lib/postgresql/data
  backend:
    container_name: backend
    ports:
      - "8000:8000"
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        SECRET_KEY: secret
        DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public&connection_timeout=300
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev --name init && node server.js"

volumes:
  quiz-db: