services:
  db:
    container_name: db
    image: postgres:16
    ports:
      - "4000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - quiz-db:/var/lib/postgresql/data

volumes:
  quiz-db: